application: zxweve
version: 4
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: myproject.wsgi.application

- url: /stylesheets
  static_dir: stylesheets

libraries:
- name: django
  version: 1.5
